config/routes.rb
Simplebeer::Application.routes.draw do
  root to: "home#index"
  %w(privacy subscribe terms).each do |page|
    get page, to: "home##{page}", as: page
  end

  resources :brews, :users

  # ---------------------------- DANGER ZONE ---------------------------- #

  # These routes handle user authentication and subscriptions.
  # Only edit these routes if you know what you're doing. Thanks!

  # Devise Routes for Admin Users
  devise_for :admin_users, controllers: {
    sessions: "admin/sessions"
  }

  # Devise Routes for Users
  devise_for :users, controllers: {
    confirmations:      "authentication/confirmations",
    invitations:        "authentication/invitations",
    omniauth_callbacks: "authentication/omniauth_callbacks",
    passwords:          "authentication/passwords",
    registrations:      "authentication/registrations",
    sessions:           "authentication/sessions",
    unlocks:            "authentication/unlocks"
  }

  # LetterOpener for Emails
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/email"
  end

  # Sidekiq Monitoring
  require "sidekiq/web"
  authenticate :admin_user do
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_authorization_check

  def index
  end

  def privacy
    @title = "Privacy Policy"
  end

  def subscribe
    @title = "Subscribe"
  end

  def terms
    @title = "Terms of Service"
  end
end

app/views/home/_monthly_kits.html.erb
<div class="monthly-kits">
  <h2>What shows up each month?</h2>

  <ul>
    <li>Pre-measured ingredients</li>
    <li>Easy to follow, step-by-step instructions</li>
    <li>Sanitizer</li>
    <li>More bottle caps!</li>
  </ul>
</div>

app/views/home/_starter_kit.html.erb
<div id="starter-kit" class="in-the-box">
  <h2>What’s in the Starter Kit?</h2>

  <p>
    If you’ve never attempted brewing beer before, our starter kit is for you.
    We include everything you need to start brewing beer. Even the bottles!
  </p>

  <ul>
    <li>1 gallon glass fermentation jug with stopper</li>
    <li>Airlock</li>
    <li>Thermometer strip</li>
    <li>(12) 12oz bottles with caps</li>
    <li>Bottle capper</li>
    <li>Brew bag</li>
    <li>Funnel</li>
    <li>Racking cane with siphon hose</li>
    <li>Large faced bi-metal thermometer</li>
    <li>Blow off hose</li>
    <li>(2) Cleaning brushes</li>
  </ul>
</div>

app/views/home/index.html.erb
<% content_for :hero do %>
  <section class="hero">
    <div class="container">
      <h1>Take the <span class="problem"><span>confusion</span></span> out of brewing beer.</h1>

      <p>
        We provide you with everything you need to brew a perfect gallon of beer each month,
        including easy to follow instructions.
        Our Starter Kit includes all of the hardware you need to get going and
        a three month subscription.
      </p>

      <h3>Be the first to find out when we start shipping!</h3>

      <!-- Begin MailChimp Signup Form -->
      <div id="mc_embed_signup">
        <form action="//beer.us10.list-manage.com/subscribe/post?u=c555d74e15c7af3cde2eb8337&amp;id=8bac3d8d0b" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
          <div id="mc_embed_signup_scroll">
            <div class="mc-field-group">
              <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" placeholder="email@domain.com">
              <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">
            </div>
          	<div id="mce-responses" class="clear">
          		<div class="response" id="mce-error-response" style="display:none"></div>
          		<div class="response" id="mce-success-response" style="display:none"></div>
          	</div>
            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;"><input type="text" name="b_c555d74e15c7af3cde2eb8337_8bac3d8d0b" tabindex="-1" value=""></div>
          </div>
        </form>
      </div>
      <script type="text/javascript" src="//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js"></script><script type="text/javascript">(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
      <!--End mc_embed_signup-->
    </div>
  </section>
<% end %>

<section class="kits">
  <h2>Need the Starter Kit or have you done this before?</h2>

  <div class="starter-kit">
    <h3>The Starter Kit - $150</h3>

    <%= image_tag("starter_kit.png") %>

    <ul>
      <li><strong>Three month subscription included</strong></li>
      <li>1 gallon glass fermentation jug with stopper</li>
      <li>Airlock</li>
      <li>Thermometer strip</li>
      <li>(12) 12oz bottles with caps</li>
      <li>Bottle capper</li>
      <li>Brew bag</li>
      <li>Funnel</li>
      <li>Racking cane with siphon hose</li>
      <li>Large faced bi-metal thermometer</li>
      <li>Blow off hose</li>
      <li>(2) Cleaning brushes</li>
    </ul>
  </div>

  <div class="monthly-kit">
    <h3>Monthly Kit - $25/mo.</h3>

    <%= image_tag("monthly_kit.png") %>

    <ul>
      <li>Pre-measured ingredients</li>
      <li>Easy to follow, step-by-step instructions</li>
      <li>Sanitizer</li>
      <li>More bottle caps!</li>
    </ul>
  </div>
</section>

<section class="hero why">
  <div class="container">
    <h2>So why Simple Beer?</h2>

    <div class="instructions them">
      <h3>Their Instructions</h3>

      <%= image_tag("instructions_them.png") %>
    </div>

    <div class="instructions us">
      <h3>Our Instructions</h3>

      <%= image_tag("instructions_us.png") %>
    </div>

    <p>
      Easy to follow instructions and precisely measured ingredients
      make brewing your first gallon of beer incredibley easy!
    </p>
  </div>
</section>

<% content_for :scripts do %>
  <script>
    var words = [
      "guesswork",
      "headache"
    ];
    var lastWord = words[0];

    function updateProblem(problems) {
      var problem = problems.pop();

      $('.problem span').animate({
        opacity: 0
      }, 700, 'swing', function() {
        $('.problem span').text(problem);

        $('.problem span').animate({
          opacity: 1
        }, 700, 'swing', function() {
          if (problem !== lastWord) {
            setTimeout(function() {
              updateProblem(problems);
            }, 2500);
          }
        });
      });
    }

    setTimeout(function() {
      updateProblem(words);
    }, 2500);
  </script>
<% end %>

app/views/home/privacy.html.erb
<div class="title">
  <h1>Privacy Policy</h1>
</div>
<div class="outer-container">
  <p>
    The privacy policy goes here.
  </p>
</div>

app/views/home/subscribe.html.erb
<h1 class="problem">Brewing beer is hard</h1>

<p class="solve-problem">
  Simple Beer solves this problem by providing you with
  everything needed to brew a perfect gallon of beer each month.
</p>

<p class="noob">
  If it’s your first time brewing, we recommend buying our
  <a href="#starter-kit">Starter Kit</a> with the shipment
  for your first brew.
</p>

<%= form_tag brews_path, method: :get, class: "sign-up" do %>
  <ul>
    <li>
      <%= radio_button_tag(:kit, :yes, selected: true) %>
      <%= label_tag(:kit_yes, "I’m new to this. I need the starter kit!") %>
    </li>
    <li>
      <%= radio_button_tag(:kit, :no) %>
      <%= label_tag(:kit_no, "I’ve done this before. I just need ingredients.") %>
    </li>
  </ul>

  <button>
    <span class="monthly-price">
      Sign up for <strong>$25 / month</strong>
    </span>
    <small class="first-month">
      First Month: <span>$100</span> with starter kit
    </small>
  </button>
<% end %>

<%= render partial: "monthly_kits" %>
<%= render partial: "starter_kit" %>

<% content_for :scripts do %>
  <script>
    $(document).ready(function () {
      $('input:radio[name="kit"]').change(function () {
        if ($(this).val() === 'yes') {
          $('.first-month').show();
        } else {
          $('.first-month').hide();
        }
      });
    });
  </script>
<% end %>

app/views/home/terms.html.erb
<div class="title">
  <h1>Terms of Service</h1>
</div>
<div class="outer-container">
  <p>
    The terms of service go here.
  </p>
</div>